// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyjpmypavkuohyrjzpzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5anBteXBhdmt1b2h5cmp6cHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTY4MjUsImV4cCI6MjA3MjI5MjgyNX0.bSQVb36NZuHQiXiIo93fzSN5YDQd5lkKz3abh_c448s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});